# Generated by Django 4.0.4 on 2022-04-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='releseDate',
            new_name='releaseDate',
        ),
    ]
