# Generated by Django 4.0.4 on 2022-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_actorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('releaseDate', models.DateField()),
                ('numberOfActors', models.IntegerField()),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='actorList',
            new_name='Actor',
        ),
        migrations.DeleteModel(
            name='movieList',
        ),
    ]
