# Generated by Django 4.0.4 on 2022-04-24 13:15

from django.db import migrations
from ..models import Movie

def addData(apps,schema_editor):
    record = Movie.objects.create(title="Spy", description="latest release", releaseDate="2022-04-20",
                                  numberOfActors=4, upvote=0, downvote=0)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_actor_movie'),
    ]

    operations = [
        migrations.RunPython(addData),
    ]
