# Generated by Django 4.0.4 on 2022-04-25 06:25

from django.db import migrations
from ..models import Movie

def newMovie(apps,schema_editor):
    movie = Movie.objects.create(title="Harry Potter", description="Magic", releaseDate="2001-06-06", numberOfActors=1)

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220424_1845'),
    ]

    operations = [
        migrations.RunPython(newMovie),
    ]
